# Author: Mitch Allen
# File Taskfile.yml

# See: https://taskfile.dev

version: '3'

vars:
  SCOPE: mitchallen # change for your npm scope

tasks:

  # list all tasks (even those without a desc)
  # default: task --list-all

  # only list tasks with a desc
  default: task --list

  get-scope:
    cmds:
      - echo "SCOPE = $SCOPE"
    silent: true

  build-all:
    desc: Build all packages
    cmds:
      - echo "===== BUILD ALL ====="
      - npm run build:all
    silent: true

  build-one:
    # task build-one -- alpha
    desc: Build one - task build-one -- alpha
    cmds:
      - npm run build -w @{{.SCOPE}}/{{.CLI_ARGS}}
    silent: false

  clean-all:
    desc: Clean all packages
    cmds:
      - echo "===== CLEAN ALL ====="
      - npm run clean:all
    silent: true

  clean-one:
    # task clean-one -- alpha
    desc: Build clean - task clean-one -- alpha
    cmds:
      - npm run clean -w @{{.SCOPE}}/{{.CLI_ARGS}}
    silent: false

  test-all:
    desc: Test all packages
    deps: [build-all]
    cmds:
      - echo "===== TEST ALL ====="
      - npm test -ws --if-present
    silent: true

  test-clean-all:
    desc: Clean and test all packages
    deps: [clean-all, test-all]
    silent: true

  test-one:
    # task test-one -- alpha
    desc: Test one - task test-one -- alpha
    cmds:
      - npm run test -w @{{.SCOPE}}/{{.CLI_ARGS}}
    silent: false

  add-package:
    # task add-package -- delta
    desc: Add a workspace package - task add-package -- delta
    cmds:
      - npm init --scope=@{{.SCOPE}} -w ./packages/{{.CLI_ARGS}} -y
      - npm install --save-dev @cucumber/cucumber ts-node @types/cucumber -w @{{.SCOPE}}/{{.CLI_ARGS}}
      - npm install --save-dev chai @types/chai -w @{{.SCOPE}}/{{.CLI_ARGS}}
      # TODO - add steps to update scripts, etc
    silent: false
    # jq check added for future expansion
    preconditions:
      - sh: jq --version > /dev/null
        msg: "jq not installed"




